name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v4
      - uses: yoshi389111/github-profile-3d-contrib@0.9.0
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
      - name: Commit & Push
        run: |
          git config user.name yesjm-dev 
          git config user.email wudals0708@naver.com
          git remote set-url origin https://github.com/${{ github.repository }}.git
          echo ${GITHUB_TOKEN}
          echo ${{ github.repository }}
          git add -A .
          git commit -m "generated" || echo "No changes to commit"
          git push https://${GITHUB_TOKEN}@github.com/yesjm-dev/yesjm-dev.git
