name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    env:
      PERSONAL_TOKEN: ${{ secrets.TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: yoshi389111/github-profile-3d-contrib@0.9.0
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          USERNAME: ${{ github.repository_owner }}

      - name: DEBUG check token
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "PERSONAL_TOKEN is ${PERSONAL_TOKEN:0:5}"

      - name: Commit & Push
        run: |
          git config user.name yesjm-dev 
          git config user.email wudals0708@naver.com

          git remote set-url origin https://x-access-token:${PERSONAL_TOKEN}@github.com/${{ github.repository }}.git

          git add -A .
          git commit -m "generated" || echo "No changes to commit"
          git push origin HEAD
